-- =========================================================
-- PHÂN HỆ 2 - CREATE USER / SCHEMA
-- Nhóm: 06
-- Schema: QLYTE_06
-- =========================================================

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


-- Xóa User nếu đã tồn tại
BEGIN
    EXECUTE IMMEDIATE 'DROP USER QLYTE_06 CASCADE';
EXCEPTION 
    WHEN OTHERS THEN 
        IF SQLCODE != -1918 THEN 
            RAISE;
        END IF;
END;
/

-- Tạo scheme chính cho Phân hệ 2
CREATE USER QLYTE_06 IDENTIFIED BY 123;

-- Cấp quyền cơ bản 
GRANT CREATE SESSION TO QLYTE_06;
GRANT CREATE TABLE TO QLYTE_06;
GRANT CREATE VIEW TO QLYTE_06;
GRANT CREATE PROCEDURE TO QLYTE_06;
GRANT CREATE TRIGGER TO QLYTE_06;
GRANT CREATE SEQUENCE TO QLYTE_06;

-- Quota
ALTER USER QLYTE_06 QUOTA UNLIMITED ON USERS;

-- Quyen can cho VPD
GRANT EXECUTE ON DBMS_RLS TO QLYTE_06;

-- Quyen can cho FGA audit
GRANT EXECUTE ON DBMS_FGA TO QLYTE_06;

-- Neu lam OLS, phan nay co the can chay bang LBACSYS/SYS rieng
GRANT EXECUTE ON SA_SYSDBA TO QLYTE_06;
GRANT EXECUTE ON SA_COMPONENTS TO QLYTE_06;
GRANT EXECUTE ON SA_LABEL_ADMIN TO QLYTE_06;
GRANT EXECUTE ON SA_USER_ADMIN TO QLYTE_06;
GRANT EXECUTE ON CHAR_TO_LABEL TO QLYTE_06;

SELECT *
FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'QLYTE_06';

CONN QLYTE_06/123@localhost:1521/XEPDB1;
SHOW USER;